config/routes.rb
Rails.application.routes.draw do

  root to: 'tops#index'

  get '/bookmarks', to: 'bookmarks#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :url, presence: true,
                  format: /\A#{URI::regexp(%w(http https))}\z/

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    redirect_to users_path
  end

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to user_path(current_user)
    else
      render 'users/show'
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update(bookmark_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to user_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:title, :url)
  end

  def correct_user
    @bookmark = current_user.bookmarks.find_by(id: params[:id])
    unless @bookmark
      redirect_to current_user
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]

    if login(email, password)
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)

    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @user = current_user

    if logged_in?
      @bookmark = current_user.bookmarks.build
      @bookmarks = current_user.bookmarks.order('created_at DESC')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @bookmark = @user.bookmarks.build
    @bookmarks = @user.bookmarks.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end

  end

  def destroy
    @user = User.find_by(id: session[:user_id])
    @user.destroy
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmarks.html.erb
<% bookmarks.each do |bookmark| %>

  <%= bookmark.title %>：<%= bookmark.url %>

<% end %>

app/views/bookmarks/edit.html.erb
<h1><%= @bookmark.title %>の編集ページ</h1>

<%= form_for(@bookmark) do |f| %>

  <div>
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title %>
  </div>
  
  <div>
    <%= f.label :url, 'URL' %>
    <%= f.text_field :url %>
  </div>
  
  <div>
    <%= f.submit '保存' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>BookmarkApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/index.html.erb
<h1>BookMark application.</h1>
<p>ブックマークを管理するアプリ。</p>
<% if logged_in? %>
  <div>ログイン中のユーザー：<%= @user.name %></div>
  <div><%= link_to 'マイページへ', @user %></div>
  </div><%= link_to 'ログアウト', logout_path, method: :delete %></div>
  
<% else %>
  <p><%= link_to 'ユーザー登録', signup_path %> or <%= link_to 'ログイン', login_path %>.</p>

<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報の編集</h1>

<%= form_for(@user) do |f| %>
  <div>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :email, 'Email' %>
    <%= f.email_field :email %>
  </div>
  
  <div>
    <%= f.submit '保存' %>
  </div>
  
  <div>
    <%= link_to 'アカウントの削除', @user ,method: :delete, data: { confirm: "本当に削除しますか？" } %>
  </div>
  <footer><%= link_to 'マイページへ', user_path %></footer>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<p>ログイン中のユーザー：<%= current_user.name %></p>
<div><%= link_to 'ログアウト', logout_path, method: :delete %></div>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.id, user %>：<%= user.name %></li>
  <% end %>
</ul>

<!--<%= link_to  %>-->

app/views/users/new.html.erb
<h1>ユーザー登録ページ</h1>

<%= form_for(@user) do |f| %>
  <div>
    <%= f.label :name, 'name' %>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :email, 'Email' %>
    <%= f.email_field :email %>
  </div>
  
  <div>  
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password %>
  </div>
  
  <div>
    <%= f.label :password_confirmation, 'パスワード確認' %>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <%= f.submit 'Sign up' %>
<% end %>

<div>
  <%= link_to 'ログインページへ', login_path %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>の詳細ページ</h1>

<% if current_user.id == @user.id %>
  <div><%= link_to 'ユーザー情報の編集', edit_user_path(@user) %></div>
  <div><%= link_to 'ログアウト', logout_path, method: :delete %></div>

  <h2>ブックマークを登録する</h2>
  <%= form_for(@bookmark) do |f| %>

    <div>
      <%= f.label :title, 'タイトル' %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :url, 'URL' %>
      <%= f.text_field :url %>
    </div>

    <%= f.submit '登録' %>
  <% end %>

<% end %>

<h2><%= @user.name %>のブックマーク</h2>

<% @bookmarks.each do |bookmark| %>
  <ul>
    <li>
      <%= bookmark.title %>：<%= link_to bookmark.url, bookmark.url %>
      <% if current_user == @user %>
        ／<%= link_to '編集', edit_bookmark_path %>・
        <%= link_to '削除', bookmark, method: :delete, data: { confirm: "本当に削除しますか？" } %>
      <% end %>
    </li>
  </ul>
<% end %>
<%= link_to 'ユーザー一覧ページへ', users_path %>
<footer><small><%= link_to 'トップページへ', root_url %></small></footer>